# Generated by Django 4.2.7 on 2024-11-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_news_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
