# Generated by Django 4.2.7 on 2024-11-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_advertisement_author_remove_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('tech', 'Technology'), ('sports', 'Sports'), ('business', 'Business'), ('health', 'Health'), ('entertainment', 'Entertainment')], default='general', max_length=50),
        ),
    ]
