# Generated by Django 4.2.7 on 2024-11-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Technology', 'Technology'), ('Sports', 'Sports'), ('Health', 'Health'), ('Politics', 'Politics'), ('Local News', 'Local News'), ('World News', 'World News')], default='general', max_length=50),
        ),
    ]
